services:
  backend:
    build: .
    command: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - ./config/secrets.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./my-tavus-app
    command: npm start
    volumes:
      - ./my-tavus-app:/app
    ports:
      - "3000:3000"
