services:
  backend:
    build:
      context: ./backend
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    env_file:
      - ./config/secrets.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./my-tavus-app
    command: npm run preview
    volumes:
      - ./my-tavus-app:/app
    ports:
      - "3000:3000"
